### ISSUE TITLE
`checkoutApi.createCheckout` won't ask for shipping address

### ISSUE THREAD

**Issue by nichoth** [square/connect-nodejs-sdk#105]
`ask_for_shipping_address` always returns as `false` in the response regardless of what is passed in and the page with the checkout does not have a shipping address as well. In this file, https://github.com/nichoth/whammy/blob/square/functions/create-order.js#L68, we pass in `true` as a value, but the API call always returns false.

Not sure what repo is for the API side of things, posting here b/c I'm using the node library.

**Comment by StephenJosey** [comment]
I noticed you have the `createCheckout` call commented out, but I also noticed you do not have quotes around "ask_for_shipping_address" which may be causing the issue? Could you let me know if that resolves it? If not I can escalate and dig into this further. Thanks!

**Comment by nichoth** [comment]
Thank you for looking. I tried it again with quotes and it's still the same response -- no shipping address fields in the checkout page. Plus i got a link to the exact commit it's using so it wont be in a random state

https://github.com/nichoth/whammy/blob/804898572b8c5dd1a04151bef6f2e35062028aa8/functions/create-order.js#L90

**Comment by StephenJosey** [comment]
So are you actually getting a success? I see a few problems:

1. Searching our logs for the idempotency_key in your repo seems to always be a failure (unauthorized, invalid location, etc).
2. Using the same idempotency_key will not get you a different result; you should be generating a new one each time or else no matter how much you change the request, you'll still get the same response. I see this one in over 100 different CreateCheckout requests since yesterday.

Let me know if that doesn't help either though.

**Comment by nichoth** [comment]
So the response returns 200 ok, but still no shipping address. This is after changing the idempotency key (thanks for noticing that) 

https://github.com/nichoth/whammy/blob/checkout/functions/create-order.js#L72

response: 
```js
ask_for_shipping_address: false
checkout_page_url: "https://connect.squareupsandbox.com/v2/checkout?c=CBASEOuzsxDyS7VyW0qVqW1j-9w&l=PR4NVQPCRMEYP"
created_at: "2020-08-05T05:10:29Z"
id: "CBASEOuzsxDyS7VyW0qVqW1j-9w"
order: {location_id: "PR4NVQPCRMEYP", id: "NNEYRVVUcWjjJThuEwSspCqcuaB", source: {…}, line_items: Array(1), net_amounts: {…}, …}
```

**Comment by StephenJosey** [comment]
Ah I see the issue. You're passing in parameters to `CreateCheckoutRequest` when it doesn't need parameters, so a lot of fields are being ignored.

The correct way to make this work would just be:

```
var body = createBody({ locationId, lineItems })
checkoutApi.createCheckout(locationId, _body)
  .then(function (res) {
    console.log('**checkout successful**', res);
    console.log('******shipping*****', res.checkout.ask_for_shipping_address)
    return cb(null, {
        statusCode: 200,
        body: JSON.stringify(res)
    })
  }, function onErr (err) {
    console.error('errriii', err);
    cb(null, {
        statusCode: 500,
        body: JSON.stringify(err)
    })
  })

// your checkout request is also missing an extra "order" field, so it should be like:
function createBody ({ locationId, lineItems }) {
    return {
        "idempotency_key": '' + randomBytes(20),
        "redirect_url": "http://localhost:8888/",
        "ask_for_shipping_address": true,
        "order": {
            "order": {
              "idempotency_key": '' + randomBytes(20),
              "location_id": locationId,
              "line_items": lineItems.map(item => {
                  return xtend(item, { quantity: item.quantity + '' })
              })
            }
        },
        "merchant_support_email": "merchant+support@website.com",
        "pre_populate_buyer_email": "example@email.com",
    }
}
```
Let me know if that still doesn't work. I tested it out and got it working but made a few changes (like ad-hoc items etc for simplicity).

**Comment by nichoth** [comment]
I see, I switched things around the way you had illustrated and it works now! I'm no longer calling `SquareConnect.CreateCheckoutRequest`, but just using the in-file function `createBody`, with an additional field of `order`.

https://github.com/nichoth/whammy/blob/checkout/functions/create-order.js

Thank you for looking at my source code. It's odd that the symptom was an unexpected response body vs returning an error. 

Now to figure out how to have square automatically add a shipping cost/tax if possible.

thanks again
