### ISSUE TITLE
Insufficient permissions error when using production

### ISSUE THREAD

**Issue by nichoth** [square/connect-nodejs-sdk#106]
This may not be a bug but when i use the production credentials in the app I get the following in response to a `createOrder` call:
```
 text: '{"errors": [{"code": "FORBIDDEN","detail": "You have insufficient permissions to perform that action.","category": "AUTHENTICATION_ERROR"}]}\n',
```

Not sure what could be a problem here, everything is exactly the same except that i switched the .env vars to the production credentials.

This is the file where the call happens:
https://github.com/nichoth/whammy/blob/5bd6c72bcc64e143599b031607af79fee4ee0b86/functions/create-order.js#L121

**Comment by jessdelacruzsantos** [comment]
If your environment credentials are set properly. The issue may lie in your permissions. You need the ORDER_WRITE permission is you are using oauth.

Here's the technical reference page for createOrder: https://developer.squareup.com/reference/square/orders-api/create-order

**Comment by sseaman** [comment]
This SDK is now in maintenance mode and will only received security updates.  Please leverage the new SDK, https://www.npmjs.com/package/square.   

If you issues still persists, please feel free to open a new ticket.
