### ISSUE TITLE
SquareConnect.TeamApi is not a constructor

### ISSUE THREAD

**Issue by orik-foxface** [square/connect-nodejs-sdk#108]
Trying to use the example from https://github.com/square/connect-nodejs-sdk/blob/master/docs/TeamApi.md#searchTeamMembers

Generates this error. Other apis (transactions, items, labor, location, etc.) work correctly.

**Comment by StephenJosey** [comment]
What version of the SDK are you using? Team API was introduced in 4.20200625.0 (which came out in June), so you need to be using at least that version or else it wouldn't exist.

**Comment by orik-foxface** [comment]
4.20200812.2

**Comment by StephenJosey** [comment]
Can you provide a code snippet without your access token? I just copied/pasted the above request with the above version and it worked successfully.

**Comment by orik-foxface** [comment]
var bodyParser = require('body-parser');
var express = require('express');
const path = require("path");
var fs = require('fs');
var app = express();
var SquareConnect = require('square-connect');
var cookieParser = require('cookie-parser');

app.use(cookieParser());
app.use(express.static('public'))
app.set('data', path.join(__dirname, "data"))
app.set('views', path.join(__dirname, "views"))
app.set("view engine", "hbs")

var sandos;
var defaultClient = SquareConnect.ApiClient.instance;

var oauth2 = defaultClient.authentications['oauth2'];
oauth2.accessToken = "";

var api = new SquareConnect.CatalogApi();
var locApi = new SquareConnect.LocationsApi();
var body = new SquareConnect.SearchCatalogObjectsRequest();
var trans = new SquareConnect.TransactionsApi();
var team = new SquareConnect.TeamApi();


produces:

var team = new SquareConnect.TeamApi();
           ^

TypeError: SquareConnect.TeamApi is not a constructor
    at Object.<anonymous> (C:\Users\User\Downloads\foxone\transact.js:25:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

I don't know enough about npm/node to figure out if there could somehow be an older version of the api being used, but npm says:

C:\Users\User\Downloads\foxone>npm view square-connect version
4.20200812.2

**Comment by StephenJosey** [comment]
Yeah, that definitely doesn't produce an error for me. Do you have a `package.json` file? If so, what is `square-connect` listed at in there? You might need to update what is in there and then run `npm update` in your terminal.

**Comment by sseaman** [comment]
This SDK is now in maintenance mode and will only received security updates.  Please leverage the new SDK, https://www.npmjs.com/package/square.   

If you issue persists, please feel free to open a new issue.
