### ISSUE TITLE
"Missing the required parameter 'body' when calling completePayment"

### ISSUE THREAD

**Issue by e-ngo** [square/connect-nodejs-sdk#111]
Issue: Using `PaymentsApi.completePayment(paymentId)` yields the following error: `"Missing the required parameter 'body' when calling completePayment"`.
Expected: There should be no errors when using `PaymentsApi.completePayment(paymentId)` with a valid `paymentId`. 
Solutions: Simply pass an empty object as the body in the API, or do not throw an error for fields that are allowed to be empty.

**Comment by e-ngo** [comment]
It turns out that `PaymentsApi.completePayment(paymentId, {})` required a second parameter.

**Comment by StephenJosey** [comment]
Hi @e-ngo thanks for reporting. What version of the SDK are you currently using? I'm not seeing any code that should require the `completePayment` to have a second parameter.

**Comment by e-ngo** [comment]
Hi @StephenJosey , I am using version `square-connect@4.20200826.3`. Looking at the source code, it seems fine. But for some reason the node_modules build is requiring a second parameter. Below is the relevant code snippet I am referencing from node_modules/square-connect/src/api/PaymentsApi.js.
```
/**
   * CompletePayment
   * Completes (captures) a payment.  By default, payments are set to complete immediately after they are created.  If you set autocomplete to false when creating a payment, you can complete (capture)  the payment using this endpoint. For more information, see [Delayed Payments](/payments-api/take-payments#delayed-payments).
   * @param {String} paymentId Unique ID identifying the payment to be completed.
   * @param {module:model/CompletePaymentRequest} body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CompletePaymentResponse} and HTTP response
   */
  this.completePaymentWithHttpInfo = function(paymentId, body) {
    var postBody = body;

    // verify the required parameter 'paymentId' is set
    if (paymentId === undefined || paymentId === null) {
      throw new Error("Missing the required parameter 'paymentId' when calling completePayment");
    }

    // verify the required parameter 'body' is set
    if (body === undefined || body === null) {
      throw new Error("Missing the required parameter 'body' when calling completePayment");
    }
```

**Comment by e-ngo** [comment]
:facepalm: This was just a simple case of not having the most up-to-date package. I was using `square-connect@4.20200722.1` whereas I should have been using `4.20200826.3`. Anyways, thanks for your help @StephenJosey .
