### ISSUE TITLE
Problems with amount

### ISSUE THREAD

**Issue by ockang** [square/connect-nodejs-sdk#115]
Hello community, I have the following problem using nodejs sdk.

It turns out that a platform that processes payments of 200 usd and up.

Apparently the payments in the square system go wrong.

In my personal system they are well saved in the database with the amount entered.

The amount is sent and converted into a whole number.

Example of delivery: 1,250.00 and it becomes 1250 but in square it takes it as 12.50, I await your response, thank you

![WhatsApp Image 2020-09-27 at 18 59 58 (1)](https://user-images.githubusercontent.com/4240285/94374439-cfeae080-00fb-11eb-9d18-8e086313d16e.jpeg)

**Comment by StephenJosey** [comment]
The API takes amounts in the lowest denomination; In USD, that would be cents. Therefore, if you pass `100`, this would be equal to 100 cents or $1.00. So if you want to charge $1,250.00, you would need to pass `125000` as the amount.

**Comment by sseaman** [comment]
This SDK is now in maintenance mode and will only received security updates.  Please leverage the new SDK, https://www.npmjs.com/package/square.   

If you issue still exists, please feel free to open a new issue.
