### ISSUE TITLE
CreateOrderRequest fails to generate an object

### ISSUE THREAD

**Issue by KempfCreative** [square/connect-nodejs-sdk#116]
### Problem
Following the examples from https://github.com/square/connect-nodejs-sdk/blob/master/docs/OrdersApi.md#createorder I am unable to successfully send an object to `createOrder`. 

### Example Code
Does NOT Work due to `body` being === `exports {}`.
```
const idempotency_key = crypto.randomBytes(22).toString('hex');
const orders_api = new squareConnect.OrdersApi();
const request_fields = {
  order: {
    location_id: "sample_Location",
      line_items: [
        {
          name: reqBody.name,
          quantity: reqBody.quantity,
          total_money: {
            amount: reqBody.amount, // $1.00 charge
            currency: 'USD'
          }
        }
      ]
    },
  idempotency_key
};
const body = new squareConnect.CreateOrderRequest(request_fields);
orders_api.createOrder(body).then(function(data) {
console.log('API called successfully. Returned data: ' + data);
  res.status(200).json(data);
}, function(error) {
  console.error(error);
  res.status(error?.status ?? 502).json(error);
});
```
Works by BYPASSING `CreateOrderRequest`:
```
const idempotency_key = crypto.randomBytes(22).toString('hex');
const orders_api = new squareConnect.OrdersApi();
const request_fields = {
  order: {
    location_id: "sample_Location",
      line_items: [
        {
          name: reqBody.name,
          quantity: reqBody.quantity,
          total_money: {
            amount: reqBody.amount, // $1.00 charge
            currency: 'USD'
          }
        }
      ]
    },
  idempotency_key
};
orders_api.createOrder(request_fields).then(function(data) {
console.log('API called successfully. Returned data: ' + data);
  res.status(200).json(data);
}, function(error) {
  console.error(error);
  res.status(error?.status ?? 502).json(error);
});
```

**Comment by StephenJosey** [comment]
If you want to pass it in the constructor, this will work:
```
const body = squareConnect.CreateOrderRequest.constructFromObject(request_fields);
...
```

**Comment by KempfCreative** [comment]
@StephenJosey thanks for that bit of code. Is the expectation that this is how the API should be used, or should `CreateOrderRequest` return an object? 

Right now, `CreateOrderRequest` returns `exports {}` which will never work to implement a `createOrder` request.

**Comment by StephenJosey** [comment]
I _think_ this is the expectation currently. We use `swagger-codegen`, which is how it forms the objects as far as I understand it (see here: https://github.com/swagger-api/swagger-codegen/issues/2113).

**Comment by KempfCreative** [comment]
OK. Should I open a PR Request to update the documentation on creating a order? As it is currently, I don't believe it is clear.

**Comment by sseaman** [comment]
This SDK is now in maintenance mode and will only received security updates.  Please leverage the new SDK, https://www.npmjs.com/package/square.   

If you issue still exists, please feel free to open a new issue.
