### ISSUE TITLE
CreateCatalogImage Missing? - Feature Request or Clarification

### ISSUE THREAD

**Issue by donaldaverill** [square/connect-nodejs-sdk#119]
I'm looking for the correct way to add a catalog image using the nodejs sdk. I see that other languages (python, ruby, java, etc) have a method called CatalogApi.CreateCatalogImageAsync or something similar. I don't see anything like this in the nodejs sdk. Am I missing something? If not, is there a workaround using Axios or another library for node? Thank you.

**Comment by StephenJosey** [comment]
This is available in the new (just released) Square Node SDK: https://github.com/square/square-nodejs-sdk/blob/master/doc/api/catalog.md#create-catalog-image
