### ISSUE TITLE
API table description column: Many (all?) linked objects broken. Point to Connect v2 API reference, not GitHub SDK reference.

### ISSUE THREAD

**Issue by JohnMAustin78** [square/connect-nodejs-sdk#16]
It appears that some or all JavaScript API object text references in the API table description columns are pointing to the Connect v2 API reference instead of to objects in the connect-javascript-sdk docs.  For example, in Order.md:
[CreateOrder](#endpoint-createorder) is incorrect.  #endpoint-createorder is the _correct_ hash for the Connect v2.0 API reference (https://docs.connect.squareup.com/api/connect/v2#endpoint-createorder) but the link _should_ be pointing to the JavaScript SDK CreateOrderRequest object (https://github.com/square/connect-javascript-sdk/blob/master/docs/CreateOrderRequest.md).

It appears that all links in the description column for each of the JavaScript SDK topics in the GitHub docs are pointing to Connect V2.0 API reference topics instead of to the appropriate GitHub JavaScript SDK topics.

**Comment by sseaman** [comment]
Resolved with the release of the new Technical Reference: https://developer.squareup.com/reference/square
