### ISSUE TITLE
[Question] typescript support

### ISSUE THREAD

**Issue by ruscon** [square/connect-nodejs-sdk#19]
Do you plan to support typescript?

**Comment by StephenJosey** [comment]
We currently don't release public outlines for new releases, but you might be able to generate your own SDK using the guidelines found in our SDK specification found here: https://github.com/square/connect-api-specification 

I do see swagger codegen listing TypeScript as a supported language, so feel free to give it a try!

**Comment by mootrichard** [comment]
I know this is way late to the party here, but I've had a lot of success when generating an SDK using [`typescript-fetch`](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/typescript-fetch). 

You can run something like:
`swagger-codegen generate -i https://raw.githubusercontent.com/square/connect-api-specification/master/api.json -l typescript-fetch -o square-connect-typescript`

That should generate a folder container your typescript square-connect module.
