### ISSUE TITLE
Case for property names

### ISSUE THREAD

**Issue by cczona** [square/connect-nodejs-sdk#22]
It appears Swagger is rendering the Javascript SDK docs incorrectly. Property names in the SDK docs are being shown in camel case. However the camel case property names aren't working. Whereas underscore case property names _are_ working.

[CreateCheckoutRequest.md](https://github.com/square/connect-javascript-sdk/blob/master/docs/CreateCheckoutRequest.md) example:

> **askForShippingAddress**
> Boolean
> If `true`, Square Checkout will collect shipping information on your behalf and store that information with the transaction information in your Square Dashboard. Default: `false`

When I try `askForShippingAddress` it does not work, but when I instead use `ask_for_shipping_address` that _does_ work.

I haven't tested other languages. (Fwiw, underscore case is shown in...)
https://github.com/square/connect-php-sdk/blob/master/docs/Model/CreateCheckoutRequest.md
https://github.com/square/connect-python-sdk/blob/master/docs/CreateCheckoutRequest.md
https://github.com/square/connect-ruby-sdk/blob/master/docs/CreateCheckoutRequest.md 

(Camel case is shown in...)
https://github.com/square/connect-csharp-sdk/blob/master/docs/CreateCheckoutRequest.md
https://github.com/square/connect-java-sdk/blob/master/docs/CreateCheckoutRequest.md

**Comment by StephenJosey** [comment]
This has since been resolved, thanks for reporting.
