### ISSUE TITLE
CORS/SRI enabled

### ISSUE THREAD

**Issue by na-n** [square/connect-nodejs-sdk#42]
Hi, I'm trying to implement some cross-origin policy on the website I'm developing which uses square-connect. I've calculated a hash for your canonical script (https://js.squareup.com/v2/paymentform) but the request for the script is failing in chrome.

Developer Tools say:

- `Access to script at 'https://js.squareup.com/v2/paymentform' from origin 'https://xxxxxxxxxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

- `GET https://js.squareup.com/v2/paymentform net::ERR_FAILED`

- `sq-payment-form.js:11 Uncaught ReferenceError: SqPaymentForm is not defined
    at sq-payment-form.js:11`

.pug:
`script(type="text/javascript" src="https://js.squareup.com/v2/paymentform" integrity='sha384-34EN2lpxCUBt12wAXfAdmPQIUXKu7hxPZ9EeL4k3NJBP0Nrx6nYn/rnjPW3H8HDV', crossorigin='anonymous')`

Could you please make the endpoint CORS enabled?

It works for jQuery..
pug:
`script(src='https://code.jquery.com/jquery-3.2.1.slim.min.js', integrity='sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN', crossorigin='anonymous')`

**Comment by na-n** [comment]
Also, I'm having a problem with pci-connect.squareup.com too:

`Access to XMLHttpRequest at 'https://pci-connect.squareup.com/v2/js-error' from origin 'https://yuzzamatuzz.co.uk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

Yet I have set the relevant options in nginx to allow pci-connect.squareup.com in the Content-Security-Policy header (`connect-uri` I believe?) .. is this a sign of an issue at my end?

**Comment by StephenJosey** [comment]
Hi @na-n, thanks for the feedback! You're correct, we currently do not supply CORS headers on our response, so I'll be sure to direct this feedback to the appropriate team. I'll definitely let you know if this changes in the future, though!

**Comment by na-n** [comment]
Hi @StephenJosey, thanks for getting back on this :)

Could we make that an official feature request for your development guys?

I think it could be turned on without affecting existing customers, though admittedly I don't yet know how to do it either so I don't know how much effort would be required to make the change and roll it out.

**Comment by ian** [comment]
+1 for this.  

Am trying to build the oAuth capability entirely in React and the CORS policy is too strict.  Is there a reason this is so locked down?

**Comment by Pckool** [comment]
THis is a major blocker for my current project. Has there been any progress on this issue?

**Comment by darrenfurr** [comment]
I've run into this same problem. Are there any updates on this issue?

**Comment by darrenfurr** [comment]
> I've run into this same problem. Are there any updates on this issue?

Never you mind. I realize that this package should be used on the server or serverless (which is what I did).

**Comment by StephenJosey** [comment]
Hey everyone, just wanted to provide an update here. We are definitely looking into some short-term solutions around CORS, however I do want to point out that you shouldn't be using SRI as this would likely break your implementation. I do not have an ETA unfortunately on the timeline around this, but I will continue to keep this issue open and post updates as I have more information. 

Thanks everyone!

**Comment by StephenJosey** [comment]
Hey all, going to go ahead and close this. We've enabled CORS headers for SqPaymentForm so this should be resolved now. Please comment if you continue running into issues around this.
