### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by alchematrix0** [square/connect-nodejs-sdk#44]
At this page in docs:

https://github.com/square/connect-javascript-sdk/blob/master/docs/OrdersApi.md#type-order

The three links in this block of text:

> Creates an Order that can then be referenced as `order_id` in a request to the Charge endpoint. Orders specify products for purchase, along with discounts, taxes, and other settings to apply to the purchase. To associate a created order with a request to the Charge endpoint, provide the order's `id` in the `order_id` field of your request. You cannot modify an order after you create it. If you need to modify an order, instead create a new order with modified details. To learn more about the Orders API, see the Orders API Overview.

do not lead any where. The one in "Orders API Overview" leads to a not found page.

**Comment by StephenJosey** [comment]
Thanks for letting us know @alchematrix0! We'll take a look to get this fixed.

**Comment by brokentone** [comment]
Similarly the "OAuth access token management" link is broken in this section: https://github.com/square/connect-javascript-sdk/blob/master/docs/OAuthApi.md#obtaintoken

**Comment by sseaman** [comment]
This SDK is now in maintenance mode and will only received security updates.  Please leverage the new SDK, https://www.npmjs.com/package/square.   

Specific to your issue, we are aware of this and have it slated to be fixed in 2021.
