### ISSUE TITLE
Transaction API: shipping_address property not consistently named

### ISSUE THREAD

**Issue by rohanbhangui** [square/connect-nodejs-sdk#55]
should the sublocality be called `sublocality_1` instead of `sublocality` for consistency sake: https://github.com/square/connect-nodejs-sdk/blob/master/docs/Address.md

**Comment by StephenJosey** [comment]
Thanks for sharing this feedback. I'll pass along to the appropriate team (this is actually an API-level, not a SDK-level issue.
