### ISSUE TITLE
How can we search Order by receipt number?

### ISSUE THREAD

**Issue by CHOMNANP** [square/connect-nodejs-sdk#59]
We have a requirement where we need to search the Transaction by receipt ID.
Is it doable with Square API?

**Comment by CHOMNANP** [comment]
Basically, can we do something like this on the API?
https://www.sellercommunity.com/t5/Questions-How-To/Is-it-possible-to-search-by-transaction-ID/td-p/15492?fbclid=IwAR0qSHFGS6iWRPvg9sbryJzt-l1ZfK4CEa7Gj9SaP88OizkwygkRE92sbPY

**Comment by deanpapastrat** [comment]
Which ID are you referring to? We have transaction IDs and order IDs in the V2 API. Could you send an example?

**Comment by CHOMNANP** [comment]
Basically, we want to let user use square App for capturing the sale transaction. So here's the scenario.
- Cashier print the receipt for customer
- Customer get receipt and key in the **receipt #** (from printed receipt) to our third party app. 
- Once our third party app got the **receipt #**, we will make a query to Square API to get transaction detail. If we can find the transaction detail based on **receipt #**, we then will perform custom logic on our third party app

Here the **receipt #** which want use as reference to search for sale transaction.
![Screen Shot 2019-08-14 at 21 45 25](https://user-images.githubusercontent.com/5925050/63030696-f55b6180-bedc-11e9-9550-7b5861ea1251.png)

**Comment by deanpapastrat** [comment]
Unfortunately we don't have a way to search by receipt number today. You can look at `SearchOrders` in the API reference to see what we do support today: https://developer.squareup.com/reference/square/orders-api/search-orders
