### ISSUE TITLE
Payments API not submitting charge with customer id and source_id (formerly customer_card_id)

### ISSUE THREAD

**Issue by SSelke** [square/connect-nodejs-sdk#66]
I have tried multiple times with multiple test cards. All have no problem creating a customer_id and customer_card_id with the Customers API. However, when I try to apply a payment using these values, it does not want to work. Here is a copy of my error:

`'{"errors": [{"code": "NOT_FOUND","detail": "Card on file not found","category": "INVALID_REQUEST_ERROR"}]}\n' },`

This was not a problem with the transactions API. Also to be noted, I am using updated api keys and location ids.

**Comment by StephenJosey** [comment]
So just to confirm, you're passing in the `customer_card_id` in the `source_id` field of the Payments API? Are you also passing in the `customer_id`

Also, you using the same access token for both the `CreateCustomerCard` and `CreatePayment` calls?

**Comment by SSelke** [comment]
Yes correct. If it wasn't clear I am using the sandbox credentials for
everything. I thought it might just be an issue where the new Payments api
only wants to use a preset customer_card_id, but again this was working
before.

**Comment by StephenJosey** [comment]
Gotcha. Would you be able to provide a `customer_id` where this issue is occurring and I can take a look at our logs to see what's happening.
