### ISSUE TITLE
Rate Limit Issue

### ISSUE THREAD

**Issue by CHOMNANP** [square/connect-nodejs-sdk#68]
I have some issue where square block the IP of the server from calling to square API. I did some research and found that there a rate limit 10 request per second on Square per merchant.

Anywhere we can increase this rate limit?

Thanks,
Punleu

**Comment by StephenJosey** [comment]
Unfortunately there is no way to increase this limit for you. We typically recommend implementing a backoff algorithm when you hit these limits.

**Comment by CHOMNANP** [comment]
Thank @StephenJosey. Anyway, can you share an official link to that rate limit rule?

**Comment by StephenJosey** [comment]
Unfortunately not. You can just find the error for rate limiting in our documentation: https://developer.squareup.com/docs/api/connect/v2#type-errorcategory
