### ISSUE TITLE
payment_id in RefundPaymentRequest should be required

### ISSUE THREAD

**Issue by batbileg289** [square/connect-nodejs-sdk#74]
How do you know which payment refunding and who will be refund receiver if I don't send payment_id since payment_id is optional?

**Comment by StephenJosey** [comment]
Thanks for reporting! I've notified our Payments team (as it's an issue at the API-level, not the SDK-level). Will leave this open until it's resolved.

**Comment by StephenJosey** [comment]
This has been resolved, now. Thanks again!
