### ISSUE TITLE
Seeking for security recommendation - Nodejs singleton

### ISSUE THREAD

**Issue by shivasurya** [square/connect-nodejs-sdk#75]
Hello team,

I'm planning to use this library to connect Square API for checkout/order API purpose. As SaaS application, we tend to allow multiple tenants to connect to Square endpoint via Oauth as per documentation. looks like this nodejs sdk library is a singleton ( Afaik )
```
var SquareConnect = require('square-connect');
var defaultClient = SquareConnect.ApiClient.instance;
```
but when accessing it looks like the default client has internal reference and has single instance of the client.
```
var apiInstance = new SquareConnect.CheckoutApi();
```
Consider, in nodejs server ( express ) application is it possible that the particular instance of the application ( square API ) mixes with other similar requests and leading to a security flaw?

Can someone from the square team or experienced with the holding singleton reference of the api client can cause such issues ?

Regards,
Shivasurya

**Comment by shivasurya** [comment]
consider each and every request may initialize new client with access token and serve corresponding purpose.

**Comment by StephenJosey** [comment]
Hi @shivasurya sorry for the delay in response. You should be able to create as many instances of the `ApiClient` as you want. Ex:

```
const prodClient = new SquareConnect.ApiClient();
prodClient.basePath = 'https://connect.squareup.com';
const sandboxClient = new SquareConnect.ApiClient();
sandboxClient.basePath = 'https://connect.squareupsandbox.com';

var oauth2 = prodClient.authentications['oauth2'];
oauth2.accessToken = 'prod-access-token';

var oauth2 = sandboxClient.authentications['oauth2'];
oauth2.accessToken = 'sandbox-access-token';

console.log(prodClient.authentications['oauth2'].accessToken);
console.log(sandboxClient.authentications['oauth2'].accessToken);
```
would print:
```
prod-access-token
sandbox-access-token
```
in the terminal. If you want to create a new API instance, you would pass it to the API. Ie 
```
var apiInstance = new SquareConnect.CatalogApi(prodClient);
```

Please let me know if I misunderstood.
