### ISSUE TITLE
Typescript error: UpdateOrder signature is inaccurate.

### ISSUE THREAD

**Issue by kegbuna** [square/connect-nodejs-sdk#82]
I am getting TS errors because tslint thinks my call is wrong when I provide
```ts
await this.ordersApi.updateOrder(location.id, orderId, {...orderApiStuff});
```

it thinks it should match:

```ts
/**
     * Updates an open [Order](#type-order) by adding, replacing, or deleting fields. Orders with a `COMPLETED` or `CANCELED`
     * state cannot be updated. An UpdateOrder request requires the following:
     * - The `order_id` in the endpoint path, identifying the order to update.
     * - The latest `version` of the order to update.
     * - The [sparse order](/orders-api/manage-orders#sparse-order-objects) containing only the fields to update and the version the update is being applied to.
     * - If deleting fields, the [dot notation paths](/orders-api/manage-orders#on-dot-notation) identifying fields to clear.
     * To pay for an order, please refer to the [Pay for Orders](/orders-api/pay-for-orders) guide.
     * To learn more about the Orders API, see the [Orders API Overview](/orders-api/what-it-does).
     */
    updateOrder(body: UpdateOrderRequest): Promise<UpdateOrderResponse>;
```

but in reality the javascript matches the former signature I am using, forcing me to use ts-ignore

**Comment by kegbuna** [comment]
Actually if you look at the comments there, they do not match the actual code signature

**Comment by StephenJosey** [comment]
Thanks for reporting. I'll escalate to our SDK team and follow-up once I have more info from them.

**Comment by okenshields** [comment]
@kegbuna , the method signature since version 2.20190814.2 is as follows:
```
this.updateOrder = function(locationId, orderId, body)
```
 https://github.com/square/connect-nodejs-sdk/blob/master/src/api/OrdersApi.js#L392

And it does appear to match the API call you had.

Were you able to resolve this issue? If not, can you provide the version you were using?

**Comment by kegbuna** [comment]
I switched to Kotlin/Java, but the version I was using is:
``` "square-connect": "^2.20200122.0",```
I haven't started it up in a bit but I can give it a shot to see if I still get the error

**Comment by okenshields** [comment]
> I switched to Kotlin/Java, but the version I was using is:
> ` "square-connect": "^2.20200122.0",`
> I haven't started it up in a bit but I can give it a shot to see if I still get the error

Thanks for the information.

This is the method signature as of version 2.20200122.0: 
https://github.com/square/connect-nodejs-sdk/blob/be3ad5eb606efb613192cd9a8c3a57880968bce0/src/api/OrdersApi.js#L337

It seems both the code method signature and method description match the API call.

**Comment by michaelaird** [comment]
I believe this was a bug in the type definitions from @types/square-connect. I've submitted a correction.

**Comment by jessdelacruzsantos** [comment]
@michaelaird  Thanks for the fix. Closing for now.
