### ISSUE TITLE
iOS React Native IDFA Issue

### ISSUE THREAD

**Issue by mrpritchett** [square/connect-nodejs-sdk#85]
Does inclusion of this library trigger Apple's IDFA warnings? Can't find any mention of this in the docs nor do I find it when we GREP for the Advertising Identifier. But when we say no we don't do any advertising during the iOS submission process, we can't continue and get this warning.

> Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.

Square in-app payments and customer verification packages are the only one we could think of that might have this.

**Comment by StephenJosey** [comment]
Hey @mrpritchett thanks for reaching out. I spoke with our In-App Payments team, and yes, our SDK will trigger this warning from IDFA. We use this for security purposes, but I will ping our Documentation team to see if we can get this documented. Please let me know if you have any other questions, though!

**Comment by mrpritchett** [comment]
Thanks!
