### ISSUE TITLE
Have added the idempotency_key but still showing "Missing required parameter"

### ISSUE THREAD

**Issue by syampsijk** [square/connect-nodejs-sdk#89]
While using square create order(node js) .
Have added the idempotency_key but still showing error
 "Missing required parameter idempotency_key"

**Comment by StephenJosey** [comment]
Apologies for the delay. Can you please provide a sample request here that fails?

**Comment by StephenJosey** [comment]
Closing out, feel free to reopen with more information. Thanks!
