### ISSUE TITLE
Typescript error: completePayment body

### ISSUE THREAD

**Issue by Nabelops** [square/connect-nodejs-sdk#97]
I am getting the typescript error `expected 1 arguments, but got 2` with the following call

`return payments_api.completePayment(payment_id, body);`

However, the call fails with just the payment_id and not the body even though according to the docs the body is empty

**Comment by dgibney** [comment]
Seeing this exact same issue...

**Comment by dgibney** [comment]
[Swagger Spec](https://raw.githubusercontent.com/square/connect-api-specification/master/api.json) needs updated to match actual [API](https://developer.squareup.com/reference/square/payments-api/complete-payment) with means removing the body in param;
![image](https://user-images.githubusercontent.com/1746864/88011011-da757200-cadb-11ea-8458-4c1565d57dc2.png)

**Comment by yauri-io** [comment]
Got same problem.

**Comment by okenshields** [comment]
Thanks for reporting the issue. We are looking into this.

**Comment by brennick** [comment]
Having the same issue, this is a breaking change of the Square Connect SDK.

**Comment by jessdelacruzsantos** [comment]
Hello all, the issue is resolved with the `4.20200812.2` release. Please reach out if you encounter any other problems.
